-- phpMyAdmin SQL Dump
-- version 4.7.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: May 20, 2017 at 06:06 PM
-- Server version: 10.1.22-MariaDB
-- PHP Version: 7.1.4

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `perfumeshopdb`
--

-- --------------------------------------------------------

--
-- Table structure for table `sanpham`
--

CREATE TABLE `sanpham` (
  `idSP` int(12) NOT NULL,
  `idNH` int(12) NOT NULL DEFAULT '1',
  `idL` int(9) NOT NULL DEFAULT '1',
  `TenSP` varchar(100) NOT NULL DEFAULT '',
  `MoTa` varchar(4000) NOT NULL DEFAULT 'Chưa có mô tả',
  `NgayCapNhat` date NOT NULL DEFAULT '2017-01-12',
  `GiaBan` float NOT NULL DEFAULT '0',
  `GiaKhuyenmai` int(11) NOT NULL DEFAULT '0',
  `urlHinh` varchar(255) NOT NULL,
  `baiviet` text,
  `SoLanXem` int(4) DEFAULT '0',
  `SoLuongTonKho` int(4) DEFAULT '0',
  `GhiChu` varchar(255) DEFAULT NULL,
  `SoLanMua` int(4) DEFAULT '0',
  `AnHien` int(1) DEFAULT '1'
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

--
-- Dumping data for table `sanpham`
--

INSERT INTO `sanpham` (`idSP`, `idNH`, `idL`, `TenSP`, `MoTa`, `NgayCapNhat`, `GiaBan`, `GiaKhuyenmai`, `urlHinh`, `baiviet`, `SoLanXem`, `SoLuongTonKho`, `GhiChu`, `SoLanMua`, `AnHien`) VALUES
(1, 1, 1, 'Khác', ' ', '2017-01-01', 0, 0, '', NULL, 0, 0, NULL, 0, 1),
(2, 18, 2, 'Calvin Klein Euphoria Blossom Women', '<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Nh&atilde;n hiệu:&nbsp;<a href=\"http://perfume168.com/nuoc-hoa-calvin-klein-117-83-0-/2/1\">Nước hoa Calvin Klein</a></p>\r\n\r\n<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Xuất xứ: Mỹ &amp; Ph&aacute;p</p>\r\n\r\n<p>M&ugrave;i hương đặc trưng</p>\r\n\r\n<ul>\r\n	<li>Hương đầu: quả lựu, quả quất v&agrave;ng</li>\r\n	<li>Hương giữa: hoa phong lan, hoa mẫu đơn hồng, hoa sen</li>\r\n	<li>Hương cuối: xạ hương, hương gỗ, hổ ph&aacute;ch trắng</li>\r\n</ul>\r\n\r\n<p>Phong c&aacute;ch: thanh lịch, tinh tế, nữ t&iacute;nh</p>\r\n\r\n<p>Lấy cảm hứng từ m&ugrave;i hương tinh tế của một nụ hoa đang h&eacute; nở,&nbsp;<strong>Euphoria Blossom</strong>&nbsp;mang m&ugrave;i hương thảo dược tươi m&aacute;t v&agrave; nồng n&agrave;n, đ&aacute;nh thức mọi gi&aacute;c quan với hương thơm quyến rũ đầy huyền b&iacute;.</p>\r\n', '2017-05-14', 1755000, 1450000, 'Calvin Klein Euphoria Blossom Women_1.PNG', NULL, 20, 50, '', 10, 1),
(3, 18, 2, 'Calvin Klein Endless Euphoria Women 125ml', '<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Nh&atilde;n hiệu:&nbsp;<a href=\"http://perfume168.com/nuoc-hoa-calvin-klein-117-83-0-/2/1\">Nước hoa Calvin Klein</a></p>\r\n\r\n<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Xuất xứ: Mỹ &amp; Ph&aacute;p</p>\r\n\r\n<p><strong>Nh&oacute;m nước hoa:</strong>&nbsp;Hương hoa cỏ tr&aacute;i c&acirc;y</p>\r\n\r\n<p><strong>Độ lưu hương:</strong>&nbsp;Tạm ổn - 3 giờ đến 6 giờ</p>\r\n\r\n<p><strong>Độ toả hương:</strong>&nbsp;Gần - Toả hương trong v&ograve;ng một c&aacute;nh tay</p>\r\n\r\n<p><strong>Thời điểm khuy&ecirc;n d&ugrave;ng:</strong>&nbsp;Ng&agrave;y, Đ&ecirc;m, Xu&acirc;n</p>\r\n\r\n<p><strong>Phong c&aacute;ch:</strong>&nbsp;Quyến rũ, thu h&uacute;t, nữ t&iacute;nh</p>\r\n\r\n<p><strong>Hương đầu:</strong>&nbsp;Quả qu&yacute;t hồng, Cam Bergamot, Hoa anh đ&agrave;o</p>\r\n\r\n<p><strong>Hương giữa:</strong>&nbsp;Hoa hồng, Hoa t&iacute;m, Hoa tử đinh hương trắng</p>\r\n\r\n<p><strong>Hương cuối:</strong>&nbsp;Xạ hương, Tre, Gỗ đ&agrave;n hương</p>\r\n\r\n<p><strong>Tổng quan:</strong>&nbsp;Th&iacute;ch hợp d&ugrave;ng cho ban ng&agrave;y, v&agrave;o m&ugrave;a xu&acirc;n v&igrave; hương thơm đầy tươi tắn, tự nhi&ecirc;n chứa đựng b&ecirc;n trong n&oacute;. Chỉ cần phối hợp với một bộ c&aacute;nh th&iacute;ch hợp, th&igrave; hương nước hoa n&agrave;y chắc chắn sẽ biến bạn th&agrave;nh một thỏi nam ch&acirc;m thu h&uacute;t những &aacute;nh nh&igrave;n ngưỡng mộ cũng như những lời khen kh&ocirc;ng ngớt từ mọi người.</p>\r\n', '2017-05-14', 1755000, 1450000, 'Calvin Klein Endless Euphoria Women 125ml_1.PNG', NULL, 7, 10, '', 6, 1),
(4, 10, 1, 'Chanel Bleu De Chanel Eau De Parfum Men', '<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Nh&atilde;n hiệu:&nbsp;<a href=\"http://perfume168.com/nuoc-hoa-chanel-120-82-0-/2/1\">Nước hoa Chanel</a></p>\r\n\r\n<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Xuất xứ: Ph&aacute;p</p>\r\n\r\n<p><strong>Nh&oacute;m nước hoa:</strong>&nbsp;Hương gỗ thơm</p>\r\n\r\n<p><strong>Độ lưu hương:</strong>&nbsp;Rất l&acirc;u - Tr&ecirc;n 12 giờ</p>\r\n\r\n<p><strong>Độ toả hương:</strong>&nbsp;Gần - Toả hương trong v&ograve;ng một c&aacute;nh tay</p>\r\n\r\n<p><strong>Thời điểm khuy&ecirc;n d&ugrave;ng:</strong>&nbsp;Ng&agrave;y, Đ&ecirc;m, Xu&acirc;n, Hạ, Thu, Đ&ocirc;ng</p>\r\n\r\n<p><strong>Phong c&aacute;ch:</strong>&nbsp;Mạnh mẽ, nam t&iacute;nh, quyến rũ</p>\r\n\r\n<p><strong>Hương ch&iacute;nh:</strong>&nbsp;Hương Labdanum, Nhục đậu khấu, Gừng, C&acirc;y hoắc hương, Gỗ đ&agrave;n hương, Cỏ hương b&agrave;i, Hương gỗ, C&acirc;y bạc h&agrave;,&nbsp;Hoa nh&agrave;i, Quả bưởi,&nbsp;Quả chanh v&agrave;ng, Nhang (Hương), Hồng ti&ecirc;u,&nbsp;Gỗ tuyết t&ugrave;ng, Hổ ph&aacute;ch.</p>\r\n\r\n<p><strong>Tổng quan:</strong>&nbsp;<strong><a href=\"http://perfume168.com/nuoc-hoa/12321chanel-bleu-de-chanel-eau-de-parfum-1095\">Bleu de Chanel</a>&nbsp;Eau De Parfum</strong>&nbsp;được đ&aacute;nh gi&aacute; l&agrave; một m&ugrave;i hương nam t&iacute;nh cho ph&aacute;i mạnh với kh&aacute; nhiều điểm tốt. Với độ lưu hương l&acirc;u v&agrave; độ tỏa hương vừa phải, đ&acirc;y l&agrave; một lựa chọn tuyệt vời để sử dụng mỗi ng&agrave;y trong tất cả c&aacute;c m&ugrave;a trong năm. Ngo&agrave;i ra, m&ugrave;i hương n&agrave;y c&oacute; thể sử dụng được trong nhiều trường hợp, từ đi l&agrave;m đến d&ugrave;ng trong l&uacute;c đi chơi, dạo phố hay clubbing đều tuyệt vời.</p>\r\n', '2017-05-14', 3835000, 3050000, 'Chanel Bleu De Chanel Eau De Parfum Men_1.PNG', NULL, 10, 10, '', 5, 1),
(5, 10, 1, 'Chanel Allure Homme Sport Eau Extreme Men', '<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Nh&atilde;n hiệu:&nbsp;<a href=\"http://perfume168.com/nuoc-hoa-chanel-120-82-0-/2/1\">Nước hoa Chanel</a></p>\r\n\r\n<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Xuất xứ: Ph&aacute;p</p>\r\n\r\n<p><strong>Nh&oacute;m nước hoa:</strong>&nbsp;Hương gỗ thơm</p>\r\n\r\n<p><strong>Độ lưu hương:</strong>&nbsp;L&acirc;u - 7 giờ đến 12 giờ</p>\r\n\r\n<p><strong>Độ toả hương:</strong>&nbsp;Xa - Toả hương trong v&ograve;ng b&aacute;n k&iacute;nh 2 m&eacute;t</p>\r\n\r\n<p><strong>Thời điểm khuy&ecirc;n d&ugrave;ng:</strong>&nbsp;Ng&agrave;y, Đ&ecirc;m, Xu&acirc;n, Hạ, Thu</p>\r\n\r\n<p><strong>Phong c&aacute;ch:</strong>&nbsp;HIện đại, nam t&iacute;nh, mạnh mẽ</p>\r\n\r\n<p><strong>Hương đầu:</strong>&nbsp;C&acirc;y x&ocirc; thơm, C&acirc;y bạc h&agrave;, Quả qu&yacute;t hồng,&nbsp;C&acirc;y b&aacute;ch</p>\r\n\r\n<p><strong>Hương giữa:</strong>&nbsp;Ti&ecirc;u</p>\r\n\r\n<p><strong>Hương cuối:</strong>&nbsp;Xạ hương, Gỗ tuyết t&ugrave;ng, Gỗ đ&agrave;n hương,&nbsp;Đậu Tonka</p>\r\n\r\n<p><strong>Tổng quan:</strong>&nbsp;Một loại hương đa dụng, c&oacute; thể sử dụng tốt cả ng&agrave;y lẫn đ&ecirc;m v&agrave; v&agrave;o tất cả c&aacute;c m&ugrave;a trong năm, đặc biệt l&agrave; m&ugrave;a xu&acirc;n, Th&iacute;ch hợp với những chuyến du xu&acirc;n, hoặc đi ăn trưa c&ugrave;ng bạn b&egrave;.</p>\r\n', '2017-05-14', 2855000, 3050000, 'Chanel Allure Homme Sport Eau Extreme Men_1.PNG', NULL, 10, 40, '', 5, 1),
(6, 11, 1, 'Dior Sauvage Men', '<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Nh&atilde;n hiệu:&nbsp;<a href=\"http://perfume168.com/nuoc-hoa-dior-134-82-0-/2/1\">Nước hoa Dior</a></p>\r\n\r\n<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Xuất xứ: Ph&aacute;p</p>\r\n\r\n<p>Hương đầu: Calabria cam bergamot kế hợp ambroxan.</p>\r\n\r\n<p>Hương giữa: Long di&ecirc;n hương.</p>\r\n\r\n<p>Hương cuối: gỗ qu&iacute;.</p>\r\n\r\n<p>Phong c&aacute;ch: tươi m&aacute;t, ph&oacute;ng kho&aacute;ng, đam m&ecirc;&nbsp;</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><a href=\"http://perfume168.com/dior-134-82-0-/2/1\" target=\"_blank\">Nước hoa Dior</a>&nbsp;ra mắt&nbsp;<a href=\"http://perfume168.com/nuoc-hoa/23232dior-sauvage-men-2131\" target=\"_blank\">nước hoa Sauvage</a>&nbsp;mới của m&igrave;nh, với t&ecirc;n c&oacute; nguồn gốc từ c&aacute;c loại&nbsp;<a href=\"http://perfume168.com/dior-134-82-0-/2/1\" target=\"_blank\">Nước hoa Dior</a>&nbsp;Eau Sauvage từ năm 1966, mặc d&ugrave; cả hai kh&ocirc;ng thuộc về c&aacute;c tuyển tập. Nước hoa Dior&nbsp;<strong>Sauvage</strong>&nbsp;được lấy cảm hứng từ thi&ecirc;n nhi&ecirc;n bao la rộng lớn, khao kh&aacute;t tự do bay nhảy&nbsp;<a href=\"http://perfume168.com/\">nước hoa</a>&nbsp;.</p>\r\n', '2017-05-14', 2000000, 0, 'Dior Sauvage Men_1.PNG', NULL, 0, 0, '', 0, 1),
(7, 11, 1, 'Dior Eau Sauvage Parfum Men', '<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Nh&atilde;n hiệu:&nbsp;<a href=\"http://perfume168.com/nuoc-hoa-dior-134-82-0-/2/1\">Nước hoa Dior</a></p>\r\n\r\n<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Xuất xứ: Ph&aacute;p</p>\r\n', '2017-05-14', 1650000, 0, 'Dior Eau Sauvage Parfum Men_1.PNG', NULL, 0, 0, '', 0, 1),
(8, 11, 1, 'Dior Eau Sauvage Men(Tester)', '<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Nh&atilde;n hiệu:&nbsp;<a href=\"http://perfume168.com/nuoc-hoa-dior-134-82-0-/2/1\">Nước hoa Dior</a></p>\r\n', '2017-05-14', 1650000, 0, 'Dior Eau Sauvage Men(Tester)_1.PNG', NULL, 0, 0, '', 0, 1),
(9, 6, 3, 'Diptyque Tam Dao Eau De Parfum', '<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Nh&atilde;n hiệu:&nbsp;<a href=\"http://perfume168.com/nuoc-hoa-diptyque-1145-86-0-/2/1\">Nước Hoa Diptyque</a></p>\r\n\r\n<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Xuất xứ: Ph&aacute;p</p>\r\n\r\n<p><strong>Nh&oacute;m nước hoa:</strong>&nbsp;Hương hoa cỏ Gỗ - Xạ hương</p>\r\n\r\n<p><strong>Độ lưu hương:</strong>&nbsp;Tạm ổn - 3 giờ đến 6 giờ</p>\r\n\r\n<p><strong>Độ toả hương:</strong>&nbsp;Gần - Toả hương trong v&ograve;ng một c&aacute;nh tay</p>\r\n\r\n<p><strong>Thời điểm khuy&ecirc;n d&ugrave;ng:</strong>&nbsp;Ng&agrave;y, Đ&ecirc;m, Thu, Đ&ocirc;ng</p>\r\n\r\n<p><strong>Phong c&aacute;ch:</strong>&nbsp;Quyến rũ, gợi cảm, tinh tế</p>\r\n\r\n<p><strong>Hương đầu:</strong>&nbsp;Hoa hồng, Hoa sim, C&acirc;y b&aacute;ch &Yacute;</p>\r\n\r\n<p><strong>Hương giữa:</strong>&nbsp;Gỗ đ&agrave;n hương, Gỗ tuyết t&ugrave;ng</p>\r\n\r\n<p><strong>Hương cuối:</strong>&nbsp;Gia vị, Hổ ph&aacute;ch, Xạ hương trắng, Gỗ cẩm lai Brazil</p>\r\n\r\n<p><strong>Tổng quan:</strong>&nbsp;Đ&acirc;y l&agrave; một hương thơm kh&aacute; đa dụng, c&oacute; thể sử dụng tốt cho cả ng&agrave;y lẫn đ&ecirc;m, Độ tỏa hương l&yacute; tưởng cho hai m&ugrave;a thu, đ&ocirc;ng v&agrave; đ&ocirc;i khi l&agrave; m&ugrave;a xu&acirc;n. Th&iacute;ch hợp kể cả khi đi l&agrave;m hoặc đi chơi.</p>\r\n', '2017-05-14', 3650000, 0, 'Diptyque Tam Dao Eau De Parfum_1.PNG', NULL, 0, 0, '', 0, 1),
(10, 19, 2, 'Elie Saab Le Parfum Women', '<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Nh&atilde;n hiệu:&nbsp;<a href=\"http://perfume168.com/nuoc-hoa-elie-saab-138-83-0-/2/1\">Nước hoa Elie Saab</a></p>\r\n\r\n<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Xuất xứ: Ph&aacute;p</p>\r\n\r\n<p>M&ugrave;i hương đặc trưng:</p>\r\n\r\n<ol>\r\n	<li>Hương đầu: hoa cam</li>\r\n	<li>Hương giữa: hoa nh&agrave;i</li>\r\n	<li>Hương cuối: hoắc hương, tuyết t&ugrave;ng, hoa hồng, mật ong</li>\r\n</ol>\r\n\r\n<p>Nh&oacute;m hương: Floral<br />\r\nPhong c&aacute;ch: Nữ t&iacute;nh, dịu d&agrave;ng, thuần khiết</p>\r\n\r\n<p>Hương thơm đầu ti&ecirc;n của thương hiệu thời trang cao cấp Lebanon mang t&ecirc;n gọi&nbsp;<strong><a href=\"http://perfume168.com/nuoc-hoa/elie-saab-le-parfum-women-2056\">Elie Saab Le Parfum</a>.&nbsp;</strong>C&aacute;c th&agrave;nh phần từ&nbsp;hoa cam, hoa hồng v&agrave; mật ong ch&iacute;nh l&agrave; hạt nh&acirc;n đ&atilde; tạo n&ecirc;n m&ugrave;i hương dịu d&agrave;ng, lắng đọng cho chai nước hoa n&agrave;y.<strong>&nbsp;</strong><strong>Le Parfum</strong>&nbsp;được nh&agrave; sản xuất c&ocirc;ng bố l&agrave; cực kỳ gợi cảm v&agrave; duy&ecirc;n d&aacute;ng.&nbsp;L&agrave;n hương mở đầu&nbsp;l&agrave; sự thơm m&aacute;t của hoa cam, kế đ&ecirc;n l&agrave; hương nh&agrave;i quyến rũ. Kết th&uacute;c đầy đam m&ecirc; v&agrave; thuần khiết với sự c&oacute; mặt&nbsp;hoa hồng, mật ong ngọt ng&agrave;o hương thơm nồng ấm của của gỗ tuyết t&ugrave;ng v&agrave; hoắc hương.</p>\r\n', '2017-05-14', 1850000, 0, 'Elie Saab Le Parfum Women_1.PNG', NULL, 0, 0, '', 0, 1),
(11, 19, 2, 'Elie Saab Rose Couture', '<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Nh&atilde;n hiệu:&nbsp;<a href=\"http://perfume168.com/nuoc-hoa-elie-saab-138-83-0-/2/1\">Nước hoa Elie Saab</a></p>\r\n\r\n<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Xuất xứ: Ph&aacute;p</p>\r\n', '2017-05-14', 2650000, 0, 'Elie Saab Rose Couture_1.PNG', NULL, 0, 0, '', 0, 1),
(12, 12, 1, 'Scuderia Ferrari Racing Red Men', '<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Nh&atilde;n hiệu:&nbsp;<a href=\"http://perfume168.com/nuoc-hoa-ferrari-145-82-0-/2/1\">Nước hoa Ferrari</a></p>\r\n\r\n<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Xuất xứ: Italy</p>\r\n\r\n<p><strong>Nh&oacute;m nước hoa: Hương gỗ</strong></p>\r\n\r\n<p><strong>Độ lưu hương:</strong>&nbsp;Rất l&acirc;u - Tr&ecirc;n 8 giờ</p>\r\n\r\n<p><strong>Độ toả hương:</strong>&nbsp;Gần - Toả hương trong v&ograve;ng một c&aacute;nh tay</p>\r\n\r\n<p><strong>Thời điểm khuy&ecirc;n d&ugrave;ng:</strong>&nbsp;Ng&agrave;y, Đ&ecirc;m, Xu&acirc;n, Thu</p>\r\n\r\n<p><strong>Phong c&aacute;ch:</strong>&nbsp;Mạnh mẽ, c&aacute; t&iacute;nh</p>\r\n\r\n<p><strong>Hương đầu:</strong>&nbsp;Quả chanh xanh, Ti&ecirc;u, Ngải.</p>\r\n\r\n<p><strong>Hương giữa:</strong>&nbsp;Hoa Oải Hương, C&acirc;y đơn s&acirc;m, Hương kim loại.</p>\r\n\r\n<p><strong>Hương cuối:</strong>&nbsp;Gỗ tuyết t&ugrave;ng, Đậu Tonka, Da thuộc.</p>\r\n\r\n<p><a href=\"http://perfume168.com/nuoc-hoa-nam-182-82-0-/0/1\">Perfume168 - Nước hoa nam Scuderia Ferrari Racing Red</a>&nbsp;</p>\r\n\r\n<p>Scuderia Ferrari Racing Red bởi&nbsp;<a href=\"http://perfume168.com/nuoc-hoa-ferrari-145-82-0-/2/1\">Ferrari</a>&nbsp;với hương thơm gỗ (Woody) đặt trưng cho nam giới. Scuderia Ferrari Racing Red được đưa ra v&agrave;o năm 2013.</p>\r\n', '2017-05-14', 1250000, 0, 'Scuderia Ferrari Racing Red Men_1.PNG', NULL, 0, 0, '', 0, 1),
(13, 12, 1, 'Ferrari Black Men', '<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Nh&atilde;n hiệu:&nbsp;<a href=\"http://perfume168.com/nuoc-hoa-ferrari-145-82-0-/2/1\">Nước hoa Ferrari</a></p>\r\n\r\n<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Xuất xứ: Italy</p>\r\n\r\n<p><strong>Nh&oacute;m nước hoa:</strong>&nbsp;Hương thơm dương xỉ</p>\r\n\r\n<p><strong>Độ lưu hương:</strong>&nbsp;Tạm ổn - 3 giờ đến 6 giờ</p>\r\n\r\n<p><strong>Độ toả hương:</strong>&nbsp;Gần - Toả hương trong v&ograve;ng một c&aacute;nh tay</p>\r\n\r\n<p><strong>Thời điểm khuy&ecirc;n d&ugrave;ng:</strong>&nbsp;Ng&agrave;y, Đ&ecirc;m, Xu&acirc;n, Thu</p>\r\n\r\n<p><strong>Phong c&aacute;ch:</strong>&nbsp;Nam t&iacute;nh, thể thao, lịch l&atilde;m</p>\r\n\r\n<p><strong>Hương đầu:</strong>&nbsp;Quả mận, Quả chanh xanh, Cam Bergamot, T&aacute;o đỏ.</p>\r\n\r\n<p><strong>Hương giữa:</strong>&nbsp;Quế, Hoa nh&agrave;i, Hoa hồng, Bạch đậu khấu.</p>\r\n\r\n<p><strong>Hương cuối:</strong>&nbsp;Hổ ph&aacute;ch, Hương Va ni, Xạ hương, Gỗ tuyết t&ugrave;ng</p>\r\n\r\n<p><strong>Tổng quan:</strong>&nbsp;Th&iacute;ch hợp d&ugrave;ng cho cả ban ng&agrave;y v&agrave; ban đ&ecirc;m, v&agrave;o m&ugrave;a xu&acirc;n, thu. Hương thơm chắc chăn sẽ thu h&uacute;t được sự ch&uacute; &yacute; cho d&ugrave; bạn đang ở đ&acirc;u.</p>\r\n', '2017-05-14', 1250000, 0, 'Ferrari Black Men_1.PNG', NULL, 0, 0, '', 0, 1),
(14, 12, 1, 'Ferrari Uomo Men', '<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Nh&atilde;n hiệu:&nbsp;<a href=\"http://perfume168.com/nuoc-hoa-ferrari-145-82-0-/2/1\">Nước hoa Ferrari</a></p>\r\n\r\n<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Xuất xứ: Italy</p>\r\n\r\n<p><strong>Hương đầu:</strong>&nbsp;Quả chanh v&agrave;ng Amalfi, Cam Bergamot, C&acirc;y b&aacute;ch x&ugrave;.</p>\r\n\r\n<p><strong>Hương giữa:</strong>&nbsp;Da thuộc, Nhục đậu khấu, Gỗ tuyết t&ugrave;ng Virginia.</p>\r\n\r\n<p><strong>Hương cuối:</strong>&nbsp;Hương Labdanum Ph&aacute;p, Đậu Tonka, C&acirc;y hoắc hương.</p>\r\n\r\n<p><strong>Nh&oacute;m nước hoa:</strong>&nbsp;Hương gỗ cay nồng</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><strong>Độ tuổi khuy&ecirc;n d&ugrave;ng:</strong>&nbsp;Tr&ecirc;n 25</p>\r\n\r\n<p><strong>Năm ra mắt:</strong>&nbsp;2009</p>\r\n\r\n<p><strong>Nồng độ:</strong>&nbsp;EDT</p>\r\n\r\n<p><strong>Độ lưu hương:</strong>&nbsp;hơn 6 giờ</p>\r\n\r\n<p><strong>Độ toả hương:</strong>&nbsp;Gần - Toả hương trong v&ograve;ng một c&aacute;nh tay</p>\r\n\r\n<p><strong>Thời điểm khuy&ecirc;n d&ugrave;ng:</strong>&nbsp;kh&ocirc;ng giới hạn</p>\r\n\r\n<p><strong>Phong c&aacute;ch:</strong>&nbsp;Nam t&iacute;nh, lịch l&atilde;m</p>\r\n', '2017-05-14', 1250000, 0, 'Ferrari Uomo Men_1.PNG', NULL, 0, 0, '', 0, 1),
(15, 5, 3, 'Armani Prive Vert Malachite For men & women', '<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Nh&atilde;n hiệu:&nbsp;<a href=\"http://perfume168.com/nuoc-hoa-giorgio-armani-146-86-0-/2/1\">Nước hoa Giorgio Armani</a></p>\r\n\r\n<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Xuất xứ: Ph&aacute;p</p>\r\n\r\n<p><strong>Độ lưu hương:</strong>&nbsp;Rất l&acirc;u - Tr&ecirc;n 12 giờ</p>\r\n\r\n<p><strong>Độ toả hương:</strong>&nbsp;Rất xa - Toả hương trong v&ograve;ng b&aacute;n k&iacute;nh tr&ecirc;n 2 m&eacute;t</p>\r\n\r\n<p><strong>Thời điểm khuy&ecirc;n d&ugrave;ng:</strong>&nbsp;Ng&agrave;y, Xu&acirc;n</p>\r\n\r\n<p><strong>Phong c&aacute;ch:</strong>&nbsp;mạnh mẽ, cuốn h&uacute;t</p>\r\n\r\n<p><strong>Hương ch&iacute;nh:</strong>&nbsp;Hoa huệ, Hoa nh&agrave;i,&nbsp;Hương lục, Hương của gỗ</p>\r\n', '2017-05-14', 6800000, 0, 'Armani Prive Vert Malachite For men & women_1.PNG', NULL, 0, 0, '', 0, 1),
(16, 5, 3, 'Armani Prive Rouge Malachite Men & Women', '<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Nh&atilde;n hiệu:&nbsp;<a href=\"http://perfume168.com/nuoc-hoa-giorgio-armani-146-86-0-/2/1\">Nước hoa Giorgio Armani</a></p>\r\n\r\n<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Xuất xứ: Ph&aacute;p</p>\r\n\r\n<p><strong>Độ lưu hương:</strong>&nbsp;Rất l&acirc;u - Tr&ecirc;n 12 giờ</p>\r\n\r\n<p><strong>Độ toả hương:</strong>&nbsp;Rất xa - Toả hương trong v&ograve;ng b&aacute;n k&iacute;nh tr&ecirc;n 2 m&eacute;t</p>\r\n\r\n<p><strong>Thời điểm khuy&ecirc;n d&ugrave;ng:</strong>&nbsp;Ng&agrave;y, Đ&ecirc;m, Xu&acirc;n, Hạ, Thu, Đ&ocirc;ng</p>\r\n\r\n<p><strong>Phong c&aacute;ch:</strong>&nbsp;sang trọng, cuốn h&uacute;t</p>\r\n\r\n<p><strong>Hương ch&iacute;nh:</strong>&nbsp;Hoa huệ trắng, Hương của gỗ, Hổ ph&aacute;ch</p>\r\n', '2017-05-14', 6800000, 0, 'Armani Prive Rouge Malachite Men & Women_1.PNG', NULL, 0, 0, '', 0, 1),
(17, 5, 3, 'Armani Prive Rose D\'arabie Intense Unisex', '<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Nh&atilde;n hiệu:&nbsp;<a href=\"http://perfume168.com/nuoc-hoa-vince-camuto-1112-82-0-/2/1\">Nước hoa Armani Prive Rose </a></p>\r\n\r\n<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Xuất xứ: Mỹ</p>\r\n', '0000-00-00', 5950000, 0, 'Armani Prive Rose D\'arabie Intense Unisex_1.PNG', NULL, 0, 0, NULL, 0, 1),
(18, 13, 1, 'Givenchy Gentlemen Only Men', '<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Nh&atilde;n hiệu:&nbsp;<a href=\"http://perfume168.com/nuoc-hoa-givenchy-147-82-0-/2/1\">Nước hoa Givenchy</a></p>\r\n\r\n<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Xuất xứ: Ph&aacute;p</p>\r\n\r\n<p><strong>Hương đầu:</strong>&nbsp;Quả qu&yacute;t hồng xanh, Hồng ti&ecirc;u, Nhục đậu khấu, Gỗ Bu-l&ocirc;.</p>\r\n\r\n<p><strong>Hương giữa:</strong>&nbsp;Gỗ tuyết t&ugrave;ng, C&acirc;y hoắc hương, Cỏ hương b&agrave;i.</p>\r\n\r\n<p><strong>Hương cuối:</strong>&nbsp;Nhang (Hương), Xạ hương.</p>\r\n\r\n<p><strong>Phong c&aacute;ch:</strong>&nbsp;Nam t&iacute;nh, lịch l&atilde;m, b&iacute; ẩn</p>\r\n', '2017-05-14', 1850000, 0, 'Givenchy Gentlemen Only Men_1.PNG', NULL, 0, 0, '', 0, 1),
(19, 13, 1, 'Givenchy Gentlemen Only Absolute', '<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Nh&atilde;n hiệu:&nbsp;<a href=\"http://perfume168.com/nuoc-hoa-givenchy-147-82-0-/2/1\">Nước hoa Givenchy</a></p>\r\n\r\n<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Xuất xứ: Ph&aacute;p</p>\r\n\r\n<p><strong>Nh&oacute;m hương:&nbsp;</strong>Hương phương Đ&ocirc;ng</p>\r\n\r\n<p><strong>Độ lưu hương:</strong>&nbsp;Rất l&acirc;u&nbsp;</p>\r\n\r\n<p><strong>Độ toả hương:</strong>&nbsp;Xa - Toả hương trong v&ograve;ng b&aacute;n k&iacute;nh 2 m&eacute;t</p>\r\n\r\n<p><strong>Thời điểm khuy&ecirc;n d&ugrave;ng:</strong>&nbsp;Đ&ecirc;m, Xu&acirc;n, Đ&ocirc;ng</p>\r\n\r\n<p><strong>Phong c&aacute;ch:</strong>&nbsp;Tinh tế, thanh lịch, hiện đại</p>\r\n\r\n<p><strong>Hương đầu:</strong>&nbsp;Nghệ t&acirc;y</p>\r\n\r\n<p><strong>Hương giữa:</strong>&nbsp;Nhục đậu khấu, Quế</p>\r\n\r\n<p><strong>Hương cuối:</strong>&nbsp;Gỗ đ&agrave;n hương,&nbsp;Vanilla</p>\r\n', '2017-05-14', 2250000, 0, 'Givenchy Gentlemen Only Absolute_1.PNG', NULL, 0, 0, '', 0, 1),
(20, 9, 1, 'Gucci Guilty Intense Pour Homme', '<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Nh&atilde;n hiệu:&nbsp;<a href=\"http://perfume168.com/nuoc-hoa-gucci-149-82-0-/2/1\">Nước hoa Gucci</a></p>\r\n\r\n<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Xuất xứ: Ph&aacute;p</p>\r\n\r\n<p><strong>Nh&oacute;m nước hoa:</strong>&nbsp;Hương gỗ thơm</p>\r\n\r\n<p><strong>Độ lưu hương:</strong>&nbsp;L&acirc;u - 7 giờ đến 12 giờ</p>\r\n\r\n<p><strong>Độ toả hương:</strong>&nbsp;Gần - Toả hương trong v&ograve;ng một c&aacute;nh tay</p>\r\n\r\n<p><strong>Thời điểm khuy&ecirc;n d&ugrave;ng:</strong>&nbsp;Ng&agrave;y, Đ&ecirc;m, Thu, Đ&ocirc;ng</p>\r\n\r\n<p><strong>Phong c&aacute;ch:</strong>&nbsp;Nam t&iacute;nh, lịch l&atilde;m, quyến rũ</p>\r\n\r\n<p><strong>Hương đầu:</strong>&nbsp;Hoa Oải Hương, Ng&ograve; thơm, Quả chanh v&agrave;ng Amalfi</p>\r\n\r\n<p><strong>Hương giữa:</strong>&nbsp;Hoa cam Ch&acirc;u Phi, Hoa cam Neroli</p>\r\n\r\n<p><strong>Hương cuối:</strong>&nbsp;C&acirc;y hoắc hương, Gỗ tuyết t&ugrave;ng Virginia, Hổ ph&aacute;ch</p>\r\n\r\n<p><strong>Tổng quan:</strong>&nbsp;Đ&acirc;y l&agrave; một m&ugrave;i hương ban đ&ecirc;m, kh&aacute; linh hoạt để sử dụng v&agrave;o hầu hết c&aacute;c m&ugrave;a trong năm. Hương thơm l&yacute; tưởng cho những l&uacute;c đi chơi với bạn b&egrave; đến c&aacute;c hộp đ&ecirc;m hoặc tiệc t&ugrave;ng.</p>\r\n', '2017-05-14', 1850000, 0, 'Gucci Guilty Intense Pour Homme_1.PNG', NULL, 0, 0, '', 0, 1),
(21, 9, 1, 'Gucci Made to Measure Men', '<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Nh&atilde;n hiệu:&nbsp;<a href=\"http://perfume168.com/nuoc-hoa-gucci-149-82-0-/2/1\">Nước hoa Gucci</a></p>\r\n\r\n<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Xuất xứ: Ph&aacute;p</p>\r\n\r\n<p><strong>Nh&oacute;m nước hoa:</strong>&nbsp;Hương cay nồng phương đ&ocirc;ng</p>\r\n\r\n<p><strong>Độ lưu hương:</strong>&nbsp;Dưới 1 giờ</p>\r\n\r\n<p><strong>Độ toả hương:</strong>&nbsp;Rất gần - Thoang thoảng tr&ecirc;n l&agrave;n da</p>\r\n\r\n<p><strong>Thời điểm khuy&ecirc;n d&ugrave;ng:</strong>&nbsp;Ng&agrave;y, Đ&ecirc;m, Xu&acirc;n, Hạ, Thu</p>\r\n\r\n<p><strong>Phong c&aacute;ch:</strong>&nbsp;Lịch l&atilde;m, nam t&iacute;nh, mạnh mẽ.</p>\r\n\r\n<p><strong>Hương đầu:</strong>&nbsp;Cam Bergamot Calabria, Hoa cam Tunisia, Hoa Oải Hương, Tiểu hồi hương</p>\r\n\r\n<p><strong>Hương giữa:</strong>&nbsp;Nhục đậu khấu, Hoa s&uacute;ng, Quả mận, Quế, Quả b&aacute;ch x&ugrave;</p>\r\n\r\n<p><strong>Hương cuối:</strong>&nbsp;Hương Labdanum, C&acirc;y hoắc hương, Da thuộc, Hổ ph&aacute;ch</p>\r\n\r\n<p><strong>Tổng quan:</strong>&nbsp;Với sự c&acirc;n bằng giữa c&aacute;c m&ugrave;i hương, đ&acirc;y hứa hẹn l&agrave; một chai nước hoa kh&aacute; ổn định v&agrave; c&oacute; thể ph&ugrave; hợp với phần lớn c&aacute;c loại thời tiết trong năm. C&aacute;c bạn nam khi sử dụng m&ugrave;i hương đẳng cấp v&agrave; lịch l&atilde;m n&agrave;y sẽ như &ldquo; Hổ mọc th&ecirc;m c&aacute;nh&rdquo; khi đi l&agrave;m việc hoặc gặp đối t&aacute;c quan trọng.</p>\r\n', '2017-05-14', 900000, 0, 'Gucci Made to Measure Men_1.PNG', NULL, 0, 0, '', 0, 1),
(22, 9, 1, 'Gucci Guilty Pour Homme', '<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Nh&atilde;n hiệu:&nbsp;<a href=\"http://perfume168.com/nuoc-hoa-gucci-149-82-0-/2/1\">Nước hoa Gucci</a></p>\r\n\r\n<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Xuất xứ: Italy</p>\r\n\r\n<p><strong>Nh&oacute;m nước hoa:</strong>&nbsp;Hương gỗ thơm</p>\r\n\r\n<p><strong>Độ lưu hương:</strong>&nbsp;Tạm ổn - 3 giờ đến 6 giờ</p>\r\n\r\n<p><strong>Độ toả hương:</strong>&nbsp;Gần - Toả hương trong v&ograve;ng một c&aacute;nh tay</p>\r\n\r\n<p><strong>Thời điểm khuy&ecirc;n d&ugrave;ng:</strong>&nbsp;Ng&agrave;y, Đ&ecirc;m, Xu&acirc;n, Hạ</p>\r\n\r\n<p><strong>Phong c&aacute;ch:</strong>&nbsp;Trẻ trung, gợi cảm, nam t&iacute;nh</p>\r\n\r\n<p><strong>Hương đầu:</strong>&nbsp;Hoa Oải Hương, Quả chanh v&agrave;ng Amalfi</p>\r\n\r\n<p><strong>Hương giữa:</strong>&nbsp;Hoa cam Ch&acirc;u Phi</p>\r\n\r\n<p><strong>Hương cuối:</strong>&nbsp;C&acirc;y hoắc hương, Gỗ tuyết t&ugrave;ng Virginia</p>\r\n\r\n<p><strong>Tổng quan:</strong>&nbsp;M&ugrave;i hương nước hoa kh&aacute; đa dụng, c&oacute; thể sử dụng cho cả ng&agrave;y lẫn đ&ecirc;m v&agrave;o c&aacute;c m&ugrave;a xu&acirc;n, thu đ&ocirc;ng. Ph&aacute;i nam c&oacute; thể sử dụng những khi đi chơi hoặc hẹn h&ograve; với bạn g&aacute;i để th&ecirc;m phần l&atilde;ng mạn.</p>\r\n', '2017-05-14', 165000, 0, 'Gucci Guilty Pour Homme_1.PNG', NULL, 0, 0, '', 0, 1),
(23, 9, 1, 'Gucci Guilty Stud Limited Edition Pour Homme Men', '<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Nh&atilde;n hiệu:&nbsp;<a href=\"http://perfume168.com/nuoc-hoa-gucci-149-82-0-/2/1\">Nước hoa Gucci</a></p>\r\n\r\n<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Xuất xứ: Ph&aacute;p</p>\r\n\r\n<p><strong>Nh&oacute;m nước hoa:</strong>&nbsp;Hương gỗ thơm</p>\r\n\r\n<p><strong>Độ lưu hương:</strong>&nbsp;Rất l&acirc;u - Tr&ecirc;n 12 giờ</p>\r\n\r\n<p><strong>Độ toả hương:</strong>&nbsp;Gần - Toả hương trong v&ograve;ng một c&aacute;nh tay</p>\r\n\r\n<p><strong>Thời điểm khuy&ecirc;n d&ugrave;ng:</strong>&nbsp;Ng&agrave;y, Đ&ecirc;m, Xu&acirc;n, Hạ, Thu, Đ&ocirc;ng</p>\r\n\r\n<p><strong>Phong c&aacute;ch:</strong>&nbsp;gần gũi, s&agrave;nh điệu, nam t&iacute;nh, quyến rũ</p>\r\n\r\n<p><strong>Hương đầu:</strong>&nbsp;Hoa Oải Hương, Quả chanh v&agrave;ng</p>\r\n\r\n<p><strong>Hương giữa:</strong>&nbsp;Hoa cam</p>\r\n\r\n<p><strong>Hương cuối:</strong>&nbsp;Gỗ tuyết t&ugrave;ng, C&acirc;y hoắc hương</p>\r\n\r\n<p><strong>Tổng quan:&nbsp;</strong>Đ&acirc;y l&agrave; một hương kh&aacute; trung t&iacute;nh khi h&agrave;i h&ograve;a giữa ấm v&agrave; m&aacute;t, cay v&agrave; ngọt m&agrave; kh&ocirc;ng thi&ecirc;n hẳn về một ph&iacute;a n&agrave;o chứng tỏ Gucci Guilty Studs Pour Homme l&agrave; một anh ch&agrave;ng dễ t&iacute;nh, thoải m&aacute;i nhưng lu&ocirc;n c&oacute; sự mạnh mẽ ẩn b&ecirc;n trong.</p>\r\n', '2017-05-14', 1850000, 0, 'Gucci Guilty Stud Limited Edition Pour Homme Men_1.PNG', NULL, 0, 0, '', 0, 1),
(24, 4, 4, 'CaHermes Eau Des Merveilles 4PC', '<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Nh&atilde;n hiệu:&nbsp;<a href=\"http://perfume168.com/nuoc-hoa-bvlgari-115-84-0-/2/1\">CaHermes</a></p>\r\n\r\n<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Xuất xứ: Italy</p>\r\n', '2017-05-14', 3250000, 0, 'CaHermes Eau Des Merveilles 4PC_1.PNG', NULL, 0, 0, '', 0, 1),
(25, 4, 4, 'Hermes Terre d`Hermes Gift Set 100ml 3PC', '<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Nh&atilde;n hiệu:&nbsp;<a href=\"http://perfume168.com/nuoc-hoa-hermes-153-84-0-/2/1\">Nước hoa Hermes</a></p>\r\n\r\n<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Xuất xứ: Ph&aacute;p</p>\r\n\r\n<p>Bộ gift set&nbsp;&nbsp;Terre D`Hermes bao gồm 3 sản phẩm:<br />\r\n1. Nước hoa&nbsp;Terre D`Hermes 100ml EDT<br />\r\n2. Mini&nbsp;Terre D`Hermes 5ml EDT<br />\r\n3.&nbsp;Sữa tắm&nbsp;Terre D`Hermes 40ml<br />\r\n<br />\r\nĐược ra mắt v&agrave;o năm 2006 bởi Jean-Claude Ellena. Đ&acirc;y l&agrave;&nbsp;hương thơm rất thanh lịch d&agrave;nh cho qu&yacute; &ocirc;ng. Như một sự kết hợp giữa trời v&agrave; đất, được v&iacute; như một chuyến du h&agrave;nh xuy&ecirc;n thời gian. Bao gồm bộ ba cổ điển đầy nam t&iacute;nh: cam chanh, gỗ v&agrave; xạ hương. Hương thơm ch&iacute;nh l&agrave;: bưởi, cam, trầm t&iacute;ch (thạch anh), hạt ti&ecirc;u, hạt ti&ecirc;u hồng, l&aacute; Geranium (phong lữ thảo), hoắc hương, tuyết t&ugrave;ng, cỏ thơm vetiver v&agrave; nhựa th&ocirc;ng.&nbsp;</p>\r\n\r\n<p>M&ugrave;i hương:&nbsp;Bao gồm bộ ba cổ điển đầy nam t&iacute;nh: cam chanh, gỗ v&agrave; xạ hương. Hương thơm ch&iacute;nh l&agrave;: bưởi, cam, trầm t&iacute;ch (thạch anh), hạt ti&ecirc;u, hạt ti&ecirc;u hồng, l&aacute; Geranium (phong lữ thảo), hoắc hương, tuyết t&ugrave;ng, cỏ thơm vetiver v&agrave; nhựa th&ocirc;ng.</p>\r\n', '2017-05-14', 2850000, 0, 'Hermes Terre d`Hermes Gift Set 100ml 3PC_1.PNG', NULL, 0, 0, '', 0, 1),
(26, 4, 4, 'Hermes Terre D’Hermes GiftSet (125ml+30ml)', '<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Nh&atilde;n hiệu:&nbsp;<a href=\"http://perfume168.com/nuoc-hoa-hermes-153-84-0-/2/1\">Nước hoa Hermes</a></p>\r\n\r\n<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Xuất xứ: Ph&aacute;p</p>\r\n\r\n<p><strong><a href=\"http://perfume168.com/nuoc-hoa-bo---lkm-184-84-0-/0/1\">Bộ nước hoa</a>&nbsp;<a href=\"http://perfume168.com/nuoc-hoa/23232hermes-terre-d-hermes-men-1205\">Hermes Terre D&rsquo;Hermes</a>&nbsp;GiftSet gồm:</strong></p>\r\n\r\n<p>1. Nước hoa 125ml.</p>\r\n\r\n<p>2. Nước hoa 30ml.</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><strong>Nh&oacute;m nước hoa:</strong>&nbsp;Hương gỗ cay nồng</p>\r\n\r\n<p><strong>Độ lưu hương:</strong>&nbsp;L&acirc;u - 7 giờ đến 12 giờ</p>\r\n\r\n<p><strong>Độ toả hương:</strong>&nbsp;Gần - Toả hương trong v&ograve;ng một c&aacute;nh tay</p>\r\n\r\n<p><strong>Thời điểm khuy&ecirc;n d&ugrave;ng:</strong>&nbsp;Ng&agrave;y, Đ&ecirc;m, Xu&acirc;n, Hạ, Thu</p>\r\n\r\n<p><strong>Phong c&aacute;ch:</strong>&nbsp;Nam t&iacute;nh, chững chạc, phong trần</p>\r\n\r\n<p><strong>Hương đầu:</strong>&nbsp;Quả cam, Quả bưởi</p>\r\n\r\n<p><strong>Hương giữa:</strong>&nbsp;Ti&ecirc;u, Thi&ecirc;n tr&uacute;c quỳ</p>\r\n\r\n<p><strong>Hương cuối:</strong>&nbsp;C&acirc;y hoắc hương, Gỗ tuyết t&ugrave;ng, Cỏ hương b&agrave;i, An tức hương</p>\r\n\r\n<p><strong>Tổng quan:</strong>&nbsp;Một m&ugrave;i hương sử dụng v&agrave;o ban ng&agrave;y rất tốt, đặc biệt l&agrave; v&agrave;o m&ugrave;a xu&acirc;n v&agrave; thu. Th&iacute;ch hợp với l&agrave;m việc hoặc vui chơi m&agrave; vẫn giữ được hương thơm trong một khoảng thời gian d&agrave;i.</p>\r\n', '2017-05-14', 3250000, 0, 'Hermes Terre D’Hermes GiftSet (125ml+30ml)_1.PNG', NULL, 0, 0, '', 0, 1),
(27, 4, 4, 'Hermes Terre D\'Hermes Giftset 3PC', '<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Nh&atilde;n hiệu:&nbsp;<a href=\"http://perfume168.com/nuoc-hoa-vince-camuto-1112-82-0-/2/1\">Nước hoa Hermes Terre </a></p>\r\n\r\n<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Xuất xứ: Mỹ</p>\r\n', '0000-00-00', 2650000, 0, 'Hermes Terre D\'Hermes Giftset 3PC_1.PNG', NULL, 0, 0, NULL, 0, 1),
(28, 4, 4, 'Hermes Voyage d\'Hermes Pure Parfum Unisex Gift Set 4PC', '<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Nh&atilde;n hiệu:&nbsp;<a href=\"http://perfume168.com/nuoc-hoa-vince-camuto-1112-82-0-/2/1\">Nước hoa Hermes Voyage </a></p>\r\n\r\n<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Xuất xứ: Mỹ</p>\r\n', '0000-00-00', 3250000, 0, 'Hermes Voyage d\'Hermes Pure Parfum Unisex Gift Set 4PC_1.PNG', NULL, 0, 0, NULL, 0, 1),
(29, 1, 1, 'Jo Malon Peony & Blush Suede Cologne', '<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Nh&atilde;n hiệu:&nbsp;<a href=\"http://perfume168.com/nuoc-hoa-jo-malone-159-86-0-/2/1\">Nước hoa Jo Malone</a></p>\r\n\r\n<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Xuất xứ: Anh Quốc</p>\r\n\r\n<p><strong>Nh&oacute;m nước hoa:</strong>&nbsp;Hương hoa cỏ</p>\r\n\r\n<p><strong>Độ lưu hương:</strong>&nbsp;L&acirc;u - 7 giờ đến 12 giờ</p>\r\n\r\n<p><strong>Độ toả hương:</strong>&nbsp;Gần - Toả hương trong v&ograve;ng một c&aacute;nh tay</p>\r\n\r\n<p><strong>Thời điểm khuy&ecirc;n d&ugrave;ng:</strong>&nbsp;Ng&agrave;y, Đ&ecirc;m, Xu&acirc;n</p>\r\n\r\n<p><strong>Phong c&aacute;ch:</strong>&nbsp;Quyến rũ, gợi cảm, tinh tế</p>\r\n\r\n<p><strong>Hương đầu:</strong>&nbsp;T&aacute;o đỏ</p>\r\n\r\n<p><strong>Hương giữa:</strong>&nbsp;Hoa mẫu đơn, Hoa nh&agrave;i, Hoa c&acirc;̉m chướng, Hoa hồng</p>\r\n\r\n<p><strong>Hương cuối:</strong>&nbsp;Da lộn</p>\r\n\r\n<p><strong>Tổng quan:</strong>&nbsp;Đ&acirc;y l&agrave; một m&ugrave;i hương sử dụng tốt v&agrave;o ban ng&agrave;y, cho m&ugrave;a xu&acirc;n v&agrave; đ&ocirc;i khi l&agrave; m&ugrave;a thu. Hương thơm l&yacute; tưởng cho những l&uacute;c đi l&agrave;m cũng như mang lại một sự quyến rũ nhẹ nh&agrave;ng khi hẹn h&ograve;.</p>\r\n', '2017-05-14', 3450000, 0, 'Jo Malon Peony & Blush Suede Cologne_2.PNG', NULL, 0, 0, '', 0, 1),
(30, 1, 1, 'Jo Malone Oud & Bergamot Cologne Intense', '<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Nh&atilde;n hiệu:&nbsp;<a href=\"http://perfume168.com/nuoc-hoa-jo-malone-159-86-0-/2/1\">Nước hoa Jo Malone</a></p>\r\n\r\n<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Xuất xứ: Anh Quốc</p>\r\n\r\n<p><strong>Nh&oacute;m nước hoa:</strong>&nbsp;Hương phương đ&ocirc;ng</p>\r\n\r\n<p><strong>Độ lưu hương:</strong>&nbsp;Tạm ổn - 3 giờ đến 6 giờ</p>\r\n\r\n<p><strong>Độ toả hương:</strong>&nbsp;Gần - Toả hương trong v&ograve;ng một c&aacute;nh tay</p>\r\n\r\n<p><strong>Thời điểm khuy&ecirc;n d&ugrave;ng:</strong>&nbsp;Ng&agrave;y, Đ&ecirc;m, Xu&acirc;n, Thu, Đ&ocirc;ng</p>\r\n\r\n<p><strong>Phong c&aacute;ch:</strong>&nbsp;Độc đ&aacute;o, gợi cảm, tinh tế</p>\r\n\r\n<p><strong>Hương ch&iacute;nh:</strong>&nbsp;Gỗ tuyết t&ugrave;ng Virginia, Cam Bergamot, Quả chanh v&agrave;ng Amalfi, Quả cam, Gỗ trầm hương</p>\r\n\r\n<p><strong>Tổng quan:</strong>&nbsp;Đ&acirc;y l&agrave; một chai nước hoa kh&aacute; linh hoạt, th&iacute;ch hợp cho cả ban ng&agrave;y v&agrave; ban đ&ecirc;m, v&agrave;o hầu hết c&aacute;c m&ugrave;a trong năm. Hương thơm l&yacute; tưởng cho việc sử dụng hằng ng&agrave;y, từ những l&uacute;c đi l&agrave;m đến những khi đi chơi dạo phố c&ugrave;ng bạn b&egrave; v&agrave; người th&acirc;n.</p>\r\n', '2017-05-14', 3250000, 0, 'Jo Malone Oud & Bergamot Cologne Intense_1.PNG', NULL, 0, 0, '', 0, 1),
(31, 16, 2, 'Mancera Wild Fruits', '<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Nh&atilde;n hiệu:&nbsp;<a href=\"http://perfume168.com/nuoc-hoa-mancera-paris-1141-83-0-/2/1\">Nước Hoa Mancera Paris</a></p>\r\n\r\n<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Xuất xứ: Ph&aacute;p</p>\r\n\r\n<p><strong>Nh&oacute;m nước hoa:</strong>&nbsp;Hương hoa cỏ tr&aacute;i c&acirc;y</p>\r\n\r\n<p><strong>Độ lưu hương:</strong>&nbsp;L&acirc;u - 7 giờ đến 12 giờ</p>\r\n\r\n<p><strong>Độ toả hương:</strong>&nbsp;Xa - Toả hương trong v&ograve;ng b&aacute;n k&iacute;nh 2 m&eacute;t</p>\r\n\r\n<p><strong>Thời điểm khuy&ecirc;n d&ugrave;ng:</strong>&nbsp;Ng&agrave;y, Xu&acirc;n, Hạ</p>\r\n\r\n<p><strong>Phong c&aacute;ch:</strong>&nbsp;Cuốn h&uacute;t, quyến rũ, c&aacute; t&iacute;nh</p>\r\n\r\n<p><strong>Hương đầu:</strong>&nbsp;Chi cam chanh, Quả kim quất, Quả chanh v&agrave;ng,Quả bưởi</p>\r\n\r\n<p><strong>Hương giữa:</strong>&nbsp;Hoa t&iacute;m, Hương tr&aacute;i c&acirc;y, Quả l&yacute; chua đen, Quả đ&agrave;o, Quả t&aacute;o xanh</p>\r\n\r\n<p><strong>Hương cuối:</strong>&nbsp;Gỗ tuyết t&ugrave;ng, Xạ hương trắng</p>\r\n', '2017-05-14', 3250000, 0, 'Mancera Wild Fruits_1.PNG', NULL, 0, 0, '', 0, 1),
(32, 17, 2, 'Rose des Vents Louis Vuitton', '<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Nh&atilde;n hiệu:&nbsp;<a href=\"http://perfume168.com/nuoc-hoa-louis-vuitton-1140-83-0-/2/1\">Nước hoa Louis Vuitton</a></p>\r\n\r\n<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Xuất xứ:</p>\r\n\r\n<p><strong><a href=\"http://perfume168.com/nuoc-hoa/12321rose-des-vents-louis-vuitton-2585\" target=\"_blank\">Rose des Vents</a></strong>&nbsp;thể hiện sự kho&aacute;ng đạt của một loại hoa đ&atilde; l&agrave;m n&ecirc;n biểu tượng, hoa hồng, được tao n&ecirc;n từ 3 loại hoa hồng kh&aacute;c kh&aacute;c từ Thổ Nhĩ Kỳ, Bulgari v&agrave; chiết xuất từ hoa hồng ng&agrave;n lớp Centifolia kết hợp với hoa iris, gỗ tuyết t&ugrave;ng v&agrave; c&aacute;c loại gia vị.</p>\r\n\r\n<p><a href=\"http://perfume168.com/\" target=\"_blank\">Hương thơm</a>&nbsp;được mong đợi nhất của thương hiệu thời trang sang trọng trọng bật nhất của Ph&aacute;p&nbsp;<strong><a href=\"http://perfume168.com/nuoc-hoa-louis-vuitton-1140-83-0-/2/1\" target=\"_blank\">Louis Vuitton</a></strong>&nbsp;cuối c&ugrave;ng cũng được ra mắt v&agrave;o th&aacute;ng Ch&iacute;n năm 2016. Qu&aacute; tr&igrave;nh chuẩn bị cũng mất thời gian nhiều nhất hơn bốn năm v&agrave; cũng do nh&agrave; thiết kế nước hoa nổi tiếng nhất hiện nay đảm nhận truyền cảm hứng thổi hồn v&agrave;o bộ sưu tập gồm 7 m&ugrave;i hương quyến rũ kh&aacute;c nhau.</p>\r\n\r\n<p>Lấy cảm hứng từ tinh thần ngao du v&agrave; niềm đam m&ecirc; kh&aacute;m ph&aacute;, bộ sưu tập&nbsp;<a href=\"http://perfume168.com/\" target=\"_blank\">nước hoa</a>&nbsp;đầu ti&ecirc;n của Louis Vuitton mang tới 7 m&ugrave;i hương, 7 h&agrave;nh tr&igrave;nh kh&aacute;m ph&aacute; khứu gi&aacute;c, 7 s&aacute;ng tạo sẽ đưa người phụ nữ tới tới bất kỳ nơi n&agrave;o với h&agrave;nh tr&igrave;nh khởi nguồn từ l&agrave;n da.</p>\r\n', '2017-05-14', 7950000, 0, 'Rose des Vents Louis Vuitton_1.PNG', NULL, 0, 0, '', 0, 1),
(33, 1, 1, 'Mariah Carey M Women', '<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Nh&atilde;n hiệu:&nbsp;<a href=\"http://perfume168.com/nuoc-hoa-mariah-carey-178-83-0-/2/1\">Nước hoa Mariah Carey</a></p>\r\n\r\n<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Xuất xứ:</p>\r\n\r\n<p><strong>Hương đầu:</strong>&nbsp;Kẹo dẻo Marshmallow, Nước biển.</p>\r\n\r\n<p><strong>Hương giữa:</strong>&nbsp;Hoa sơn chi, Hoa Tiare.</p>\r\n\r\n<p><strong>Hương cuối:</strong>&nbsp;Hổ ph&aacute;ch, C&acirc;y hoắc hương, Nhang (Hương).</p>\r\n\r\n<p><strong>Phong c&aacute;ch:</strong>&nbsp;Tinh tế, trang nh&atilde;, thu h&uacute;t.</p>\r\n', '2017-05-14', 1250000, 0, 'Mariah Carey M Women_1.PNG', NULL, 0, 0, '', 0, 1),
(34, 20, 4, 'Prada Candy Florale Giftset', '<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Nh&atilde;n hiệu:&nbsp;<a href=\"http://perfume168.com/nuoc-hoa-prada-191-84-0-/2/1\">Nước hoa Prada</a></p>\r\n\r\n<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Xuất xứ: T&acirc;y Ban Nha</p>\r\n', '2017-05-14', 2650000, 0, 'Prada Candy Florale Giftset_1.PNG', NULL, 0, 0, '', 0, 1),
(35, 8, 1, 'Penhaligon\'s Portraits The Tragedy of Lord George', '<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Nh&atilde;n hiệu:&nbsp;<a href=\"http://perfume168.com/nuoc-hoa-vince-camuto-1112-82-0-/2/1\">Nước hoa Penhaligon </a></p>\r\n\r\n<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Xuất xứ: Mỹ</p>\r\n', '0000-00-00', 7950000, 0, 'Penhaligon\'s Portraits The Tragedy of Lord George_1.PNG', NULL, 0, 0, NULL, 0, 1),
(36, 8, 1, 'Penhaligon\'s Portraits The Duke', '<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Nh&atilde;n hiệu:&nbsp;<a href=\"http://perfume168.com/nuoc-hoa-vince-camuto-1112-82-0-/2/1\">Nước hoa Penhaligon </a></p>\r\n\r\n<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Xuất xứ: Mỹ</p>\r\n', '0000-00-00', 7950000, 0, 'Penhaligon\'s Portraits The Duke_1.PNG', NULL, 0, 0, NULL, 0, 1),
(37, 2, 4, 'Swarovski Aura Gift Set 3PC', '<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Nh&atilde;n hiệu:&nbsp;<a href=\"http://perfume168.com/nuoc-hoa-swarovski-1121-84-0-/2/1\">Nước hoa Swarovski</a></p>\r\n\r\n<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Xuất xứ: Ph&aacute;p</p>\r\n\r\n<p>Bộ nước hoa Swarovski Aura gổm&nbsp; sản phẩm</p>\r\n\r\n<p>1. Nước hoa 50ml eau de parfum</p>\r\n\r\n<p>2. Kem dưỡng thể 50ml</p>\r\n\r\n<p>3. V&iacute; cầm tay da</p>\r\n\r\n<p><strong>Hương đầu:</strong>&nbsp;Hoa hồng, Quả vải.</p>\r\n\r\n<p><strong>Hương giữa:</strong>&nbsp;Hoa huệ trắng.</p>\r\n\r\n<p><strong>Hương cuối:</strong>&nbsp;Xạ hương, Hổ ph&aacute;ch, An tức hương, Hồng ti&ecirc;u.</p>\r\n\r\n<p><strong>Phong c&aacute;ch:</strong>&nbsp;Tươi tắn, nữ t&iacute;nh, thu h&uacute;t</p>\r\n', '2017-05-14', 1750000, 0, 'Swarovski Aura Gift Set 3PC_1.PNG', NULL, 0, 0, '', 0, 1),
(38, 3, 4, 'Thierry Mugler Amen Set 3PC', '<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Nh&atilde;n hiệu:&nbsp;<a href=\"http://perfume168.com/nuoc-hoa-thierry-mugler-199-84-0-/2/1\">Nước hoa Thierry Mugler</a></p>\r\n\r\n<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Xuất xứ: Ph&aacute;p</p>\r\n\r\n<h3><strong><a href=\"http://perfume168.com/nuoc-hoa-bo---lkm-184-84-0-/0/1\">Bộ nước hoa nam</a>&nbsp;<a href=\"http://perfume168.com/nuoc-hoa/12321thierry-mugler-amen-2162\">Thierry Mugler Amen</a>&nbsp;GiftSet gồm:</strong></h3>\r\n\r\n<p>- Nước hoa nam Thierry Mugler A Men 100ml</p>\r\n\r\n<p>- Dầu gội Thierry Mugler A Men 50ml</p>\r\n\r\n<p>- Lăng khử m&ugrave;i Thierry Mugler A Men 20ml</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><strong>Nh&oacute;m hương:&nbsp;</strong>Oriental &ndash; Woody</p>\r\n\r\n<p><strong>Độ lưu hương:</strong>&nbsp;L&acirc;u - 7 giờ đến 12 giờ</p>\r\n\r\n<p><strong>Độ toả hương:</strong>&nbsp;Xa - Toả hương trong v&ograve;ng b&aacute;n k&iacute;nh 2 m&eacute;t</p>\r\n\r\n<p><strong>M&ugrave;i hương đặc trưng:&nbsp;</strong>Oải hương, Cam B&ecirc;gamốt, Helional, Bạc h&agrave;, Hạt c&agrave; ph&ecirc; rang, Hoắc hương, Caramen, Đậu Tonka, Nhựa đường, Xạ hương, Vani, S&ocirc;c&ocirc;la.</p>\r\n\r\n<p><strong>Thời điểm khuy&ecirc;n d&ugrave;ng:</strong>&nbsp;Ng&agrave;y, Đ&ecirc;m, Thu, Đ&ocirc;ng</p>\r\n\r\n<p><strong>Phong c&aacute;ch:&nbsp;</strong>Quyến rũ, độc đ&aacute;o</p>\r\n', '2017-05-14', 2250000, 0, 'Thierry Mugler Amen Set 3PC_1.PNG', NULL, 0, 0, '', 0, 1),
(39, 3, 4, 'Thierry Mugler Mini Alien & Angel', '<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Nh&atilde;n hiệu:&nbsp;<a href=\"http://perfume168.com/nuoc-hoa-thierry-mugler-199-84-0-/2/1\">Nước hoa Thierry Mugler</a></p>\r\n\r\n<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Xuất xứ: Ph&aacute;p</p>\r\n\r\n<p><strong><a href=\"http://perfume168.com/nuoc-hoa-bo---lkm-184-84-0-/0/1\">Bộ nước hoa</a>&nbsp;<a href=\"http://perfume168.com/nuoc-hoa-thierry-mugler-199-83-0-/2/1\">Thierry Mugler</a>&nbsp;Mini bao gồm 4 sản phẩm:</strong></p>\r\n\r\n<p>1. Thierry Mugler Angel Mini 5ml eau de parfum</p>\r\n\r\n<p>2. Thierry Mugler Angel Mini 3ml eau de toilette</p>\r\n\r\n<p>3. Thierry Mugler Alien Mini 6ml eau de parfum</p>\r\n\r\n<p>4. Thierry Mugler Alien Essence Absolue Mini 6ml eau de parfum intense</p>\r\n', '2017-05-14', 1550000, 0, 'Thierry Mugler Mini Alien & Angel_1.PNG', NULL, 0, 0, '', 0, 1),
(40, 3, 4, 'Thierry Mugler Angel Set 3x25ml Women', '<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Nh&atilde;n hiệu:&nbsp;<a href=\"http://perfume168.com/nuoc-hoa-thierry-mugler-199-84-0-/2/1\">Nước hoa Thierry Mugler</a></p>\r\n\r\n<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Xuất xứ: Ph&aacute;p</p>\r\n\r\n<p><strong><a href=\"http://perfume168.com/nuoc-hoa-bo---lkm-184-84-0-/0/1\">Bộ nước hoa</a>&nbsp;<a href=\"http://perfume168.com/nuoc-hoa/12321thierry-mugler-angel-women-1727\">Thierry Mugler Angel</a>&nbsp;gồm 3 sản phẩm:</strong></p>\r\n\r\n<p>1. Nước hoa 25ml eau de parfum</p>\r\n\r\n<p>2. Sữa tắm 25ml</p>\r\n\r\n<p>3. Dưỡng thể 25ml</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><strong>Nh&oacute;m nước hoa:</strong>&nbsp;Hương va-ni phương đ&ocirc;ng</p>\r\n\r\n<p><strong>Độ lưu hương:</strong>&nbsp;Rất l&acirc;u - Tr&ecirc;n 12 giờ</p>\r\n\r\n<p><strong>Độ toả hương:</strong>&nbsp;Rất xa - Toả hương trong v&ograve;ng b&aacute;n k&iacute;nh tr&ecirc;n 2 m&eacute;t</p>\r\n\r\n<p><strong>Thời điểm khuy&ecirc;n d&ugrave;ng:</strong>&nbsp;Ng&agrave;y, Đ&ecirc;m, Đ&ocirc;ng</p>\r\n\r\n<p><strong>Phong c&aacute;ch:</strong>&nbsp;Thu h&uacute;t, quyến rũ</p>\r\n\r\n<p><strong>Hương đầu:</strong>&nbsp;Dưa gang, Quả dừa, Quả qu&yacute;t hồng, C&acirc;y b&atilde; đậu,Hoa nh&agrave;i, Cam Bergamot, Kẹo b&ocirc;ng g&ograve;n</p>\r\n\r\n<p><strong>Hương giữa:</strong>&nbsp;Mật ong, Quả mơ, Quả m&acirc;m x&ocirc;i đen, Quả mận,Hoa phong lan, Quả đ&agrave;o, Hoa nh&agrave;i, Hoa linh lan thung lũng, Tr&aacute;i c&acirc;y đỏ, Hoa hồng</p>\r\n\r\n<p><strong>Hương cuối:</strong>&nbsp;Đậu Tonka, Hổ ph&aacute;ch, C&acirc;y hoắc hương, Xạ hương,Hương Va ni, S&ocirc; c&ocirc; la đen, Đường thắng</p>\r\n\r\n<p><strong>Tổng quan:</strong>&nbsp;Một m&ugrave;i hương m&ugrave;a lạnh nồng n&agrave;n, đầy hấp dẫn cho ph&aacute;i đẹp, đặc biệt ph&aacute;t huy t&aacute;c dụng tốt nhất v&agrave;o ban đ&ecirc;m. Chỉ cần xịt một &iacute;t nước hoa l&agrave; bạn đ&atilde; sẵn s&agrave;ng thu h&uacute;t mọi &aacute;nh nh&igrave;n với sự gợi cảm của ch&iacute;nh bản th&acirc;n.</p>\r\n', '2017-05-14', 1550000, 0, 'Thierry Mugler Angel Set 3x25ml Women_1.PNG', NULL, 0, 0, '', 0, 1),
(41, 20, 5, 'Prada Amber Pour homme Intense', '<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Nh&atilde;n hiệu:&nbsp;<a href=\"http://perfume168.com/nuoc-hoa-vince-camuto-1112-82-0-/2/1\">Nước hoa Vince Camuto</a></p>\r\n\r\n<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Xuất xứ: Mỹ</p>\r\n', '2017-05-13', 3150000, 2450000, 'Prada Amber Pour homme Intense.PNG', NULL, 15, 10, 'Không có', 1, 1),
(42, 7, 5, 'Carolina Herrera 212 CH Men Sport', '<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Nh&atilde;n hiệu:&nbsp;<a href=\"http://perfume168.com/nuoc-hoa-212-carolina-herrera-118-82-0-/2/1\">Nước hoa 212 Carolina Herrera</a></p>\r\n\r\n<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Xuất xứ: T&acirc;y Ban Nha</p>\r\n\r\n<p><strong>Nh&oacute;m nước hoa:</strong>&nbsp;Hương thơm cay nồng</p>\r\n\r\n<p><strong>Độ lưu hương:</strong>&nbsp;L&acirc;u - 7 giờ đến 12 giờ</p>\r\n\r\n<p><strong>Độ toả hương:</strong>&nbsp;Gần - Toả hương trong v&ograve;ng một c&aacute;nh tay</p>\r\n\r\n<p><strong>Thời điểm khuy&ecirc;n d&ugrave;ng:</strong>&nbsp;Ng&agrave;y, Xu&acirc;n, Hạ</p>\r\n\r\n<p><strong>Phong c&aacute;ch:</strong>&nbsp;Thể thao, nam t&iacute;nh, trang nh&atilde;.</p>\r\n\r\n<p><strong>Hương đầu:</strong>&nbsp;Cam Bergamot, C&acirc;y x&ocirc; thơm, Quả bưởi</p>\r\n\r\n<p><strong>Hương giữa:</strong>&nbsp;C&acirc;y b&aacute;ch x&ugrave;, Xuy&ecirc;n ti&ecirc;u, Hương nước biển</p>\r\n\r\n<p><strong>Hương cuối:</strong>&nbsp;Gỗ đ&agrave;n hương, Cỏ hương b&agrave;i,&nbsp;R&ecirc;u sồ</p>\r\n', '2017-05-13', 2150000, 1650000, 'Carolina Herrera 212 CH Men Sport.PNG', NULL, 5, 20, '', 5, 1),
(43, 11, 5, 'Dior Homme Intense', '<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Nh&atilde;n hiệu:&nbsp;<a href=\"http://perfume168.com/nuoc-hoa-dior-134-82-0-/2/1\">Nước hoa Dior</a></p>\r\n\r\n<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Xuất xứ: Ph&aacute;p</p>\r\n\r\n<p><strong>Nh&oacute;m nước hoa:</strong>&nbsp;Hương gỗ hoa cỏ xạ hương</p>\r\n\r\n<p><strong>Độ lưu hương:</strong>&nbsp;Rất l&acirc;u - Tr&ecirc;n 12 giờ</p>\r\n\r\n<p><strong>Độ toả hương:</strong>&nbsp;Xa - Toả hương trong v&ograve;ng b&aacute;n k&iacute;nh 2 m&eacute;t</p>\r\n\r\n<p><strong>Thời điểm khuy&ecirc;n d&ugrave;ng:</strong>&nbsp;Ng&agrave;y, Đ&ecirc;m, Thu, Đ&ocirc;ng</p>\r\n\r\n<p><strong>Phong c&aacute;ch:</strong>&nbsp;Lịch l&atilde;m, thu h&uacute;t, chững trạc</p>\r\n\r\n<p><strong>Hương đầu:</strong>&nbsp;Hoa Oải Hương</p>\r\n\r\n<p><strong>Hương giữa:</strong>&nbsp;Hoa di&ecirc;n vĩ, C&acirc;y v&ocirc;ng vang, Quả l&ecirc;</p>\r\n\r\n<p><strong>Hương cuối:</strong>&nbsp;Cỏ hương b&agrave;i, Gỗ tuyết t&ugrave;ng Virginia</p>\r\n', '2017-05-13', 3450000, 2650000, 'Dior Homme Intense.PNG', NULL, 9, 9, '', 12, 1);
INSERT INTO `sanpham` (`idSP`, `idNH`, `idL`, `TenSP`, `MoTa`, `NgayCapNhat`, `GiaBan`, `GiaKhuyenmai`, `urlHinh`, `baiviet`, `SoLanXem`, `SoLuongTonKho`, `GhiChu`, `SoLanMua`, `AnHien`) VALUES
(44, 19, 2, 'Elie Saab Le Parfum Women', '<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Nh&atilde;n hiệu:&nbsp;<a href=\"http://perfume168.com/nuoc-hoa-elie-saab-138-83-0-/2/1\">Nước hoa Elie Saab</a></p>\r\n\r\n<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Xuất xứ: Ph&aacute;p</p>\r\n\r\n<p>M&ugrave;i hương đặc trưng:</p>\r\n\r\n<ol>\r\n	<li>Hương đầu: hoa cam</li>\r\n	<li>Hương giữa: hoa nh&agrave;i</li>\r\n	<li>Hương cuối: hoắc hương, tuyết t&ugrave;ng, hoa hồng, mật ong</li>\r\n</ol>\r\n\r\n<p>Nh&oacute;m hương: Floral<br />\r\nPhong c&aacute;ch: Nữ t&iacute;nh, dịu d&agrave;ng, thuần khiết</p>\r\n', '2017-05-13', 3650000, 2850000, 'Elie Saab Le Parfum Women.PNG', NULL, 9, 10, '', 2, 1),
(45, 21, 3, 'Byredo Pulp Eau De Parfum', '<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Nh&atilde;n hiệu:&nbsp;<a href=\"http://perfume168.com/nuoc-hoa-byredo-1151-86-0-/2/1\">Nước Hoa Byredo</a></p>\r\n\r\n<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Xuất xứ: Ph&aacute;p</p>\r\n\r\n<p><strong>Nh&oacute;m nước hoa:</strong>&nbsp;Hương va-ni phương đ&ocirc;ng</p>\r\n\r\n<p><strong>Độ lưu hương:</strong>&nbsp;Rất l&acirc;u - Tr&ecirc;n 12 giờ</p>\r\n\r\n<p><strong>Độ toả hương:</strong>&nbsp;Đang cập nhật</p>\r\n\r\n<p><strong>Thời điểm khuy&ecirc;n d&ugrave;ng:</strong>&nbsp;Đ&ecirc;m, Đ&ocirc;ng</p>\r\n\r\n<p><strong>Phong c&aacute;ch:</strong>&nbsp;Trong v&ograve;ng 1 c&aacute;nh tay</p>\r\n\r\n<p><strong>Hương đầu:</strong>&nbsp;Hồng ti&ecirc;u, Hoa hồng đỏ Thổ Nhĩ Kỳ&nbsp;</p>\r\n\r\n<p><strong>Hương giữa:</strong>&nbsp;Hoa hồng đỏ Thổ Nhĩ Kỳ , Hoa c&acirc;y m&acirc;m x&ocirc;i</p>\r\n\r\n<p><strong>Hương cuối:</strong>&nbsp;Giấy c&oacute;i, Hổ ph&aacute;ch</p>\r\n', '2017-05-13', 6400000, 4950000, 'Byredo Pulp Eau De Parfum_0.PNG', NULL, 12, 6, '', 3, 1),
(46, 21, 3, 'Byredo Rose Noir_0', '<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Nh&atilde;n hiệu:&nbsp;<a href=\"http://perfume168.com/nuoc-hoa-byredo-1151-86-0-/2/1\">Nước Hoa Byredo</a></p>\r\n\r\n<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Xuất xứ: Ph&aacute;p</p>\r\n\r\n<p><strong>Nh&oacute;m nước hoa:</strong>&nbsp;Hương hoa cỏ Gỗ - Xạ hương</p>\r\n\r\n<p><strong>Độ lưu hương:</strong>&nbsp;L&acirc;u - 7 giờ đến 12 giờ</p>\r\n\r\n<p><strong>Độ toả hương:</strong>&nbsp;Gần - Toả hương trong v&ograve;ng một c&aacute;nh tay</p>\r\n\r\n<p><strong>Thời điểm khuy&ecirc;n d&ugrave;ng:</strong>&nbsp;Ng&agrave;y, Đ&ecirc;m, Xu&acirc;n, Thu</p>\r\n\r\n<p><strong>Phong c&aacute;ch:</strong>&nbsp;l&ocirc;i cuốn, l&atilde;ng mạn, gợi cảm</p>\r\n\r\n<p><strong>Hương đầu:</strong>&nbsp;Quả bưởi, Hoa lan Nam Phi.</p>\r\n\r\n<p><strong>Hương giữa:</strong>&nbsp;Hoa hồng Đan Mạch.</p>\r\n\r\n<p><strong>Hương cuối:</strong>&nbsp;Hương Labdanum, R&ecirc;u sồi, Xạ hương</p>\r\n', '2017-05-13', 6400000, 4950000, 'Byredo Rose Noir_0.PNG', NULL, 1, 7, '', 1, 1),
(47, 9, 2, 'Gucci Guilty Tester Women', '<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Nh&atilde;n hiệu:&nbsp;<a href=\"http://perfume168.com/nuoc-hoa-gucci-149-83-0-/2/1\">Nước hoa Gucci</a></p>\r\n\r\n<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Xuất xứ: Italy</p>\r\n\r\n<p><strong>Nh&oacute;m hương:</strong>&nbsp;hoa cỏ, phương Đ&ocirc;ng</p>\r\n\r\n<p><strong>Độ lưu hương:</strong>&nbsp;Tạm ổn - 3 giờ đến 6 giờ</p>\r\n\r\n<p><strong>Độ toả hương:</strong>&nbsp;Gần - Toả hương trong v&ograve;ng một c&aacute;nh tay</p>\r\n\r\n<p><strong>Thời điểm khuy&ecirc;n d&ugrave;ng:</strong>&nbsp;Ng&agrave;y, Đ&ecirc;m, Thu, Đ&ocirc;ng</p>\r\n\r\n<p><strong>Phong c&aacute;ch:</strong>&nbsp;Nữ t&iacute;nh, qu&yacute; ph&aacute;i, kh&ecirc;u gợi</p>\r\n\r\n<p><strong>Hương đầu:</strong>&nbsp;Quả qu&yacute;t hồng, Hồng ti&ecirc;u</p>\r\n\r\n<p><strong>Hương giữa:</strong>&nbsp;Hoa phong lữ, Quả đ&agrave;o, Hoa tử đinh hương</p>\r\n\r\n<p><strong>Hương cuối:</strong>&nbsp;C&acirc;y hoắc hương, Hổ ph&aacute;ch</p>\r\n\r\n<p><strong>Tổng quan:</strong>&nbsp;Một m&ugrave;i hương ban đ&ecirc;m, thể hiện khả năng tốt nhất v&agrave;o m&ugrave;a thu, nhưng bạn cũng c&oacute; thể sử dụng v&agrave;o mua đ&ocirc;ng.</p>\r\n', '2017-05-14', 1950000, 1550000, 'Gucci Guilty Tester Women.PNG', NULL, 10, 20, '', 3, 1),
(48, 9, 2, 'Gucci Bamboo Women 75ml', '<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Nh&atilde;n hiệu:&nbsp;<a href=\"http://perfume168.com/nuoc-hoa-gucci-149-83-0-/2/1\">Nước hoa Gucci</a></p>\r\n\r\n<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Xuất xứ: Italy</p>\r\n\r\n<p><strong>Nh&oacute;m hương:</strong>&nbsp;Floral</p>\r\n\r\n<p><strong>Độ lưu hương:</strong>&nbsp;Tạm ổn - 3 giờ đến 6 giờ</p>\r\n\r\n<p><strong>Độ toả hương:</strong>&nbsp;Rất gần - Thoang thoảng tr&ecirc;n l&agrave;n da</p>\r\n\r\n<p><strong>Thời điểm khuy&ecirc;n d&ugrave;ng:</strong>&nbsp;Ng&agrave;y, Đ&ecirc;m, Xu&acirc;n</p>\r\n\r\n<p><strong>Phong c&aacute;ch:</strong>&nbsp;Sang trọng, sắc sảo</p>\r\n\r\n<p><strong>Hương đầu:</strong>&nbsp;Cam Bergamot</p>\r\n\r\n<p><strong>Hương giữa:</strong>&nbsp;Hoa ngọc lan t&acirc;y, Hoa huệ Casablanca, Hoa cam</p>\r\n\r\n<p><strong>Hương cuối:</strong>&nbsp;Hổ ph&aacute;ch, Gỗ đ&agrave;n hương, Hương Va ni Tahiti</p>\r\n', '2017-05-14', 2665000, 2050000, 'Gucci Bamboo Women 75ml.PNG', NULL, 13, 5, '', 5, 1),
(49, 9, 2, 'Gucci Eau De Parfum II Women', '<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Nh&atilde;n hiệu:&nbsp;<a href=\"http://perfume168.com/nuoc-hoa-gucci-149-83-0-/2/1\">Nước hoa Gucci</a></p>\r\n\r\n<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Xuất xứ: Italy</p>\r\n\r\n<p><strong>Nh&oacute;m nước hoa:</strong>&nbsp;Hương hoa cỏ tr&aacute;i c&acirc;y</p>\r\n\r\n<p><strong>Độ lưu hương:</strong>&nbsp;Tạm ổn - 3 giờ đến 6 giờ</p>\r\n\r\n<p><strong>Độ toả hương:</strong>&nbsp;Gần - Toả hương trong v&ograve;ng một c&aacute;nh tay</p>\r\n\r\n<p><strong>Thời điểm khuy&ecirc;n d&ugrave;ng:</strong>&nbsp;Ng&agrave;y, Đ&ecirc;m, Xu&acirc;n, Hạ</p>\r\n\r\n<p><strong>Phong c&aacute;ch:</strong>&nbsp;Nữ t&iacute;nh, gợi cảm, quyến rũ</p>\r\n\r\n<p><strong>Hương đầu:</strong>&nbsp;Quả l&yacute; chua đen, Quả qu&yacute;t hồng, Tr&aacute;i c&acirc;y đỏ, C&acirc;y b&atilde; đậu,&nbsp;Cam đắng</p>\r\n\r\n<p><strong>Hương giữa:</strong>&nbsp;Hoa mẫu đơn, Hoa t&iacute;m, Quả m&acirc;m x&ocirc;i đen, Hoa nh&agrave;i, Hoa lan Nam Phi,&nbsp;Hoa linh lan thung lũng</p>\r\n\r\n<p><strong>Hương cuối:</strong>&nbsp;Xạ hương, Gỗ tuyết t&ugrave;ng, Hoa v&ograve;i voi</p>\r\n\r\n<p><strong>Tổng quan:</strong>&nbsp;Một m&ugrave;i hương tự nhi&ecirc;n nhẹ nh&agrave;ng. Ph&ugrave; hợp với ph&aacute;i đẹp muốn m&igrave;nh c&oacute; một m&ugrave;i hương cơ thể dịu ngọt, nhưng lại quyễn rũ v&agrave; hấp dẫn</p>\r\n', '2017-05-14', 2250000, 1850000, 'Gucci Eau De Parfum II Women.PNG', NULL, 25, 22, '', 12, 1),
(50, 9, 2, 'Gucci Flora by Gucci Edt Women', '<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Nh&atilde;n hiệu:&nbsp;<a href=\"http://perfume168.com/nuoc-hoa-gucci-149-83-0-/2/1\">Nước hoa Gucci</a></p>\r\n\r\n<p><img src=\"http://perfume168.com/Images/ImageSource/checkicon.jpg\" />&nbsp;Xuất xứ: Italy</p>\r\n\r\n<p><strong>Nh&oacute;m hương:</strong>&nbsp;hoa cỏ</p>\r\n\r\n<p><strong>Độ lưu hương:</strong>&nbsp;Tạm ổn - 3 giờ đến 6 giờ</p>\r\n\r\n<p><strong>Độ toả hương:</strong>&nbsp;Gần - Toả hương trong v&ograve;ng một c&aacute;nh tay</p>\r\n\r\n<p><strong>Thời điểm khuy&ecirc;n d&ugrave;ng:</strong>&nbsp;Ng&agrave;y, Đ&ecirc;m, Xu&acirc;n</p>\r\n\r\n<p><strong>Phong c&aacute;ch:</strong>&nbsp;Nữ t&iacute;nh, l&ocirc;i cuốn, gợi cảm</p>\r\n\r\n<p><strong>Hương đầu:</strong>&nbsp;Chi cam chanh, Hoa mẫu đơn, Quả qu&yacute;t hồng</p>\r\n\r\n<p><strong>Hương giữa:</strong>&nbsp;Hoa mộc t&ecirc;, Hoa hồng</p>\r\n\r\n<p><strong>Hương cuối:</strong>&nbsp;Gỗ đ&agrave;n hương, C&acirc;y hoắc hương, Hồng ti&ecirc;u</p>\r\n\r\n<p><strong>Tổng quan:</strong>&nbsp;Một m&ugrave;i hương nhẹ nh&agrave;ng, sử dụng tốt cho ban ng&agrave;y nhất l&agrave; vao m&ugrave;a xu&acirc;n. th&iacute;ch hợp khi đi l&agrave;m hoặc đơn giản l&agrave; bạn muốn c&oacute; một m&ugrave;i hương &ocirc;m lấy cơ thể trong suốt một ng&agrave;y d&agrave;i</p>\r\n', '2017-05-14', 2015000, 1650000, 'Gucci Flora by Gucci Edt Women.PNG', NULL, 12, 22, '', 10, 1);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `sanpham`
--
ALTER TABLE `sanpham`
  ADD PRIMARY KEY (`idSP`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `sanpham`
--
ALTER TABLE `sanpham`
  MODIFY `idSP` int(12) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=712;COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
